// Generated by https://quicktype.io

export interface Trabajador {
  // id: number;
  // clave_empleado: string;
  // status: number;
  // d_estatus: null | string;
  // nombre: string;
  // fecha_nacimiento: string;
  // sexo: string;
  // RFC: string;
  // CURP: string;
  // imss: string;
  // domicilio: string;
  // colonia: string;
  // poblacion: string;
  // estado: string;
  // lugar_nacimiento: string;
  // codigo_postal: string;
  // telefono1: string;
  // telefono2: string;
  // email: string;
  // idDepartamento: number;
  // descripcion_departamento: string;
  // idPuesto: number;
  // descripcion_puesto: string;
  // observaciones: string;
  // nivel_escolaridad: number;
  // d_nivelEscolaridad: string;
  // fecha_baja: string;
  // motivo_baja: number;
  // d_motiboBaja: string;
  // motivo_baja_especificacion: string;
  // fecha_alta: string;
  // fecha_cambio: string;

  //-------------------------------------------
  id: number;
  clave_empleado: string;
  status: number;
  nombre: string;
  fecha_nacimiento: string;
  sexo: string;
  RFC: string;
  CURP: string;
  imss: string;
  domicilio: string;
  colonia: string;
  poblacion: string;
  estado: string;
  lugar_nacimiento: string;
  codigo_postal: string;
  telefono1: string;
  telefono2: string;
  email: string;
  idDepartamento: number;
  idPuesto: number;
  observaciones: string;
  nivel_escolaridad: number;
  fecha_baja: string;
  motivo_baja: number;
  motivo_baja_especificacion: string;
  clave_perfil: number;
  fecha_alta: string;
  fecha_cambio: string;
  password: string;
  nombreAgenda: string;
  aliasTickets: string;
}
